### PR TITLE
Updated findiff feedstock version to 0.10.0

### PR DESCRIPTION
**Pull request by og113**
So, I wrote a recipe for the latest version of findiff (https://github.com/conda-forge/staged-recipes/pull/23768), and then realised this feedstock already existed, so I am proposing an update here instead.

@conda-forge-admin please rerender

### CODE REVIEW

**Comment by og113** [comment]
I see there are a bunch of other PRs failing for findiff updates. I do not quite understand what is failing, but note that the single-file recipe for version 0.10.0 on https://github.com/conda-forge/staged-recipes/pull/23768 passed all the checks.

**Comment by og113** [comment]
Removing the patch (`0001-exclude-tests-from-setup.py-for-conda-forge-compatib.patch`) and references to it was enough to resolve the previous issues. Version 0.10.0 of findiff doesn't need this patch.

**Review by tnigon — COMMENTED** [review]
@og113 Do most of the changes in this PR come from the conda-forge feedstock template? I'm not all that familiar with the process anymore.

**Review by tnigon — APPROVED** [review]
Considering the checks pass, looks good to me! Thanks for doing this.

**Comment by og113** [comment]
Yes, exactly. In my commits, I think I made 4 changes to lines of code, and removed the patch. The rest is automatic stuff.

**Comment by og113** [comment]
Sorry to bother @tnigon. Just wanted to check what the plan was wrt merging this PR? Cheers :)

**Comment by tnigon** [comment]
@og113 I approved, and it should be good for you to go ahead and merge. Let me know if there's anything else to discuss. Thanks again for taking the lead on this.

**Comment by og113** [comment]
@tnigon, thanks! However, I don't have write access to merge pull requests on this repo.

**Comment by tnigon** [comment]
@og113 Ah, that makes sense. I'm not the repo owner, and I don't have control over the settings; but I will go ahead and merge for you! Sorry for the misunderstanding!

**Comment by tnigon** [comment]
@og113 Do you think this branch should be merged with the latest automated PR so that all the checks are run? See all the PRs at: https://github.com/conda-forge/findiff-feedstock/pulls

**Comment by tnigon** [comment]
@conda-forge-admin, please lint

**Comment by og113** [comment]
That could be a good idea. Probably the reason the automated ones failed was just the same patch that needed dropping.

**Pull request merged**
